/* config.h.cmake — generated by CMake, do not edit directly.
   This mirrors the autoheader-generated config.h used by the Autotools build.
   All macros here correspond to guards already used in the TuxMath source code. */

#ifndef CONFIG_H
#define CONFIG_H

/* ------------------------------------------------------------------
   Package identification
   ------------------------------------------------------------------ */
#define PACKAGE        "@PACKAGE_NAME@"
#define VERSION        "@TUXMATH_VERSION@"
#define PACKAGE_STRING "@PACKAGE_NAME@-@TUXMATH_VERSION@"
#define PACKAGE_BUGREPORT "tuxmath-devel@lists.sourceforge.net"

/* ------------------------------------------------------------------
   Library availability
   ------------------------------------------------------------------ */

/* Define to 1 if libt4k_common is available */
#cmakedefine HAVE_LIBT4K_COMMON 1

/* Define to 1 if libRSVG is available (SVG image loading) */
#cmakedefine HAVE_RSVG 1

/* Define to 1 if SDL3_net is available (LAN multiplayer) */
#cmakedefine HAVE_LIBSDL_NET 1

/* ------------------------------------------------------------------
   Internationalization (NLS / gettext)
   ------------------------------------------------------------------ */

/* Define to 1 if NLS (gettext) is enabled */
#cmakedefine ENABLE_NLS 1

/* Define to 1 if gettext is available */
#cmakedefine HAVE_GETTEXT 1

/* ------------------------------------------------------------------
   Platform / compiler
   ------------------------------------------------------------------ */

/* Define to 1 when building natively on MinGW/Windows.
   Activates WIN32-specific code paths (single-arg mkdir, Registry
   access for home dir, .txt file extensions for config files, etc.) */
#cmakedefine BUILD_MINGW32 1

/* Define to 1 if putenv() is available (always true on MinGW) */
#cmakedefine HAVE_PUTENV 1

/* ------------------------------------------------------------------
   POSIX functions (absent or incomplete on MinGW)
   ------------------------------------------------------------------ */

/* Define to 1 if scandir() is available */
#cmakedefine HAVE_SCANDIR

/* Define to 1 if alphasort() is available */
#cmakedefine HAVE_ALPHASORT

/* Define to 1 if localtime_r() is available */
#cmakedefine HAVE_LOCALTIME_R

/* ------------------------------------------------------------------
   Standard headers
   ------------------------------------------------------------------ */

/* Define to 1 if <error.h> is available (glibc-specific) */
#cmakedefine HAVE_ERROR_H

/* Define to 1 if <stdint.h> is available */
#cmakedefine HAVE_STDINT_H

/* Define to 1 if <unistd.h> is available */
#cmakedefine HAVE_UNISTD_H

/* ------------------------------------------------------------------
   iconv
   ------------------------------------------------------------------ */

/* Define if the second argument of iconv() is const char** */
#cmakedefine ICONV_SECOND_ARGUMENT_IS_CONST
#ifdef ICONV_SECOND_ARGUMENT_IS_CONST
#  define ICONV_CONST const
#else
#  define ICONV_CONST
#endif

#endif /* CONFIG_H */
